// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zOaxW_LDdYpHsGEscCBP7x6v4Xbi1aU',
    appId: '1:679604839287:web:14e9993609b8eed99ff772',
    messagingSenderId: '679604839287',
    projectId: 'recipeme-ea6d6',
    authDomain: 'recipeme-ea6d6.firebaseapp.com',
    storageBucket: 'recipeme-ea6d6.firebasestorage.app',
    measurementId: 'G-NFQRE15NJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9es-jGrl-evBQOln0EXlRpA8SPs-IPjg',
    appId: '1:679604839287:android:1556663b9f2a028c9ff772',
    messagingSenderId: '679604839287',
    projectId: 'recipeme-ea6d6',
    storageBucket: 'recipeme-ea6d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdJx4whHSd5-ffPBYeyaT20BC4kgX_EAY',
    appId: '1:679604839287:ios:a1d5c8a60bcc3c409ff772',
    messagingSenderId: '679604839287',
    projectId: 'recipeme-ea6d6',
    storageBucket: 'recipeme-ea6d6.firebasestorage.app',
    iosBundleId: 'com.example.recipeme',
  );
}
